Repository myriadsocial/myriad-dashboard, pull requests merged in 2022-08, with the labels that each got.

#35 fix: pagination on user & post table
  .storybook/main.js
  .storybook/preview.js
  package.json
  public/favicon.ico
  public/favicon.png
  public/favicon.svg
  public/icons/index.ts
  public/icons/myriad-icon.png
  src/api/DELETE_Reports.ts
  src/api/GET_Reports.ts
  src/api/PATCH_Reports.ts
  src/api/posts.ts
  src/api/users.ts
  src/components/atoms/AvatarWithName/index.tsx
  src/components/atoms/Button/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/components/organisms/Table/index.tsx
  src/interface/index.ts
  src/interface/report-category-type.enum.ts
  src/interface/report-status-type.enum.ts
  src/interface/report-type.enum.ts
  src/interface/table-type.enum.ts
  src/layout/ContentLayout.tsx
  src/middleware.ts
  src/pages/_app.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/pages/index.tsx
  src/stories/Button.stories.tsx
  src/stories/Button.tsx
  src/stories/Header.stories.tsx
  src/stories/Header.tsx
  src/stories/Introduction.stories.mdx
  src/stories/Page.stories.tsx
  src/stories/Page.tsx
  src/stories/assets/code-brackets.svg
  src/stories/assets/colors.svg
  src/stories/assets/comments.svg
  src/stories/assets/direction.svg
  src/stories/assets/flow.svg
  src/stories/assets/plugin.svg
  src/stories/assets/repo.svg
  src/stories/assets/stackalt.svg
  src/stories/button.css
  src/stories/header.css
  src/stories/page.css
  src/utils/dateFormatter/index.ts
  yarn.lock
Labels: enhancement

#36 feat: setup .env
  next.config.js
  package.json
  src/api/DELETE_Reports.ts
  src/api/PATCH_Reports.ts
  src/api/axiosInstance.ts
  src/config/index.ts
Labels: enhancement

#40 feat: added page instance and edit instance
  next.config.js
  public/icons/ExperianceGray.svg
  public/icons/IcCalender.svg
  public/icons/IcCopy.svg
  public/icons/PostGray.svg
  public/icons/UserGray.svg
  public/icons/index.ts
  src/api/GET_Healtcheck.ts
  src/api/axiosInstance.ts
  src/components/molecules/CardEditInstance/index.tsx
  src/components/molecules/CardInstanceLeft/index.tsx
  src/components/molecules/CardInstanceRight/index.tsx
  src/components/molecules/Modal/index.tsx
  src/components/organisms/Header/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/components/organisms/Table/index.tsx
  src/constans/array.ts
  src/middleware.ts
  src/pages/dashboard/cluster/index.tsx
  src/pages/dashboard/instance/edit.tsx
  src/pages/dashboard/instance/index.tsx
  src/pages/dashboard/instance/instance.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
  src/pages/maintenance/index.tsx
  src/utils/colors/index.ts
  tsconfig.json
Labels: enhancement

#42 ci: fix deployment
  .github/workflows/deployer.yml
Labels: CI

#43 feat: added healthcheck
  src/pages/api/healthcheck.ts
Labels: enhancement

#44 ci: fix deployment
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: CI

#45 update axios instansce
  .gitignore
  next.config.js
  src/api/GET_Notifications.ts
  src/api/axiosInstance.ts
  src/components/atoms/DropdownFilter/index.tsx
  src/components/molecules/CardEditInstance/index.tsx
  src/components/organisms/Header/index.tsx
  src/pages/dashboard/instance/edit.tsx
Labels: enhancement

#47 fix next config
  next.config.js
Labels: bug

#48 ci: disabled sleuth
  .env-template
  .github/workflows/deployer.yml
  .github/workflows/release.yml
  next.config.js
Labels: CI

#49 update axios instance
  src/api/axiosInstance.ts
Labels: bug

#50 integration dashboard notification
  src/api/DELETE_Reports.ts
  src/api/GET_Notifications.ts
  src/api/PATCH_Reports.ts
  src/api/axiosInstance.ts
  src/components/atoms/ListAllNotifications/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/constans/array.ts
  src/interface/NotificationsInterface.ts
  src/pages/dashboard/notification/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/user/responded.tsx
Labels: enhancement

#51 fix bug user & post on progress
  .DS_Store
  next.config.js
  src/api/DELETE_Reports.ts
  src/api/GET_Healtcheck.ts
  src/api/GET_Notifications.ts
  src/api/GET_Reports.ts
  src/api/GET_ReportsDetail.ts
  src/api/PATCH_Reports.ts
  src/api/axiosInstance.ts
  src/components/atoms/ListReporter/index.tsx
  src/components/molecules/EmptyState/index.tsx
  src/components/molecules/Modal/index.tsx
  src/components/organisms/Siderbar/index.tsx
  src/constans/array.ts
  src/interface/UserInterface.ts
  src/pages/api/[...all].ts
  src/pages/dashboard/notification/index.tsx
  src/pages/dashboard/post/index.tsx
  src/pages/dashboard/post/responded.tsx
  src/pages/dashboard/user/index.tsx
  src/pages/dashboard/user/responded.tsx
Labels: bug

#52 ci: added new env auth
  .github/workflows/deployer.yml
  .github/workflows/release.yml
Labels: CI

#53 feat: added auth url
  .env-template
  next.config.js
  package.json
  src/api/axiosInstance.ts
  yarn.lock
Labels: enhancement

#54 fix: auth url
  .env-template
  next.config.js
Labels: wontfix

#60 fix: notification filter
  next.config.js
  src/api/DELETE_Reports.ts
  src/api/GET_Notifications.ts
  src/api/GET_Reports.ts
  src/api/GET_ReportsDetail.ts
  src/api/PATCH_Reports.ts
  src/api/axiosInstance.ts
  src/constans/array.ts
  src/pages/api/[...all].ts
Labels: enhancement
